# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.summary.outputs.images }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Build images
        env:          
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$GITHUB_REF_NAME" == "${{ github.event.repository.default_branch }}" ]]; then
            tag="latest"        
          else
            tag="$GITHUB_REF_NAME"
          fi
          
          echo "Branch: $GITHUB_REF_NAME"
          echo "Tag: $tag"
          echo " "
          dir
          ls
          cat ./docker-compose.yaml
          docker compose pull || echo 'image cache not found'
          docker compose build --build-arg TOKEN=$TOKEN --build-arg TAG=$tag
      
      - name: Push images
        run: docker compose push
